//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Leaveword {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.DropDownList ddlFk_News_Id;
		protected global::System.Web.UI.WebControls.ObjectDataSource ObjectDataSource1;
		protected global::System.Web.UI.WebControls.TextBox txtContents;
		protected global::System.Web.UI.WebControls.TextBox txtFK_Users_Id;
		protected global::System.Web.UI.WebControls.TextBox txtAddTimes;
		protected global::System.Web.UI.WebControls.Button btnSave;
		protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
