//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.PermisssionsNodes {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblId;
		protected global::System.Web.UI.WebControls.DropDownList ddlFk_Permissions_Id;
		protected global::System.Web.UI.WebControls.ObjectDataSource ObjectDataSource1;
		protected global::System.Web.UI.WebControls.DropDownList ddlFk_Nodes_Id;
		protected global::System.Web.UI.WebControls.ObjectDataSource ObjectDataSource2;
		protected global::System.Web.UI.WebControls.Button btnSave;
		protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
